# Generated by Django 3.1.2 on 2020-10-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categorie',
        ),
    ]
