# Generated by Django 3.1.2 on 2020-10-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='completed',
        ),
    ]
